const mongoose = require('mongoose');

const scheduledPostSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    platform: {
        type: String,
        required: true,
        enum: ['LinkedIn', 'Twitter', 'Instagram']
    },
    content: {
        type: String,
        required: true
    },
    scheduledFor: {
        type: Date,
        required: true
    },
    status: {
        type: String,
        enum: ['scheduled', 'published', 'failed', 'draft'],
        default: 'scheduled'
    },
    contentType: {
        type: String,
        enum: ['Company Updates', 'Thought Leadership', 'Personal', 'Educational', 'Product'],
        default: 'Personal'
    },
    autoGenerated: {
        type: Boolean,
        default: false
    },
    metadata: {
        tone: String,
        wordCount: Number,
        characterCount: Number,
        estimatedEngagement: Number,
        hashtags: [String]
    },
    recurringScheduleId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'RecurringSchedule',
        default: null
    }
}, {
    timestamps: true
});

// Index for efficient queries
scheduledPostSchema.index({ userId: 1, scheduledFor: 1 });
scheduledPostSchema.index({ userId: 1, status: 1 });

module.exports = mongoose.model('ScheduledPost', scheduledPostSchema);
